

//Blog requests
###
GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{
    "author": "something 2nd test",
    "title": "something 2nd",
    "url": "somethingend.com",
    "likes": 15
}

//User requests
###
GET http://localhost:3003/api/users HTTP/1.1


###
POST http://localhost:3003/api/users HTTP/1.1
content-Type: application/json

{
    "username": "bacardi",
    "name": "filipe",
    "password": "p@ssw0rd",
    "blog": []
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-Type: application/json

{
    "username": "pistaccio",
    "name": "hyunjin",
    "password": "pVsswArd",
    "blog": []
}


//Blog with UserID
###
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 15,
    "user": "607eed3ac8929512f67f03a4"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0,
  "user": "607eed3ac8929512f67f03a4"
}

//User Login
###
POST http://localhost:3003/api/login HTTP/1.1
content-Type: application/json

{
    "username": "bacardi",
    "password": "p@ssw0rd"
}   

//User Login
###
POST http://localhost:3003/api/login HTTP/1.1
content-Type: application/json

{
    "username": "pistaccio",
    "password": "pVsswArd"
}   

//POST with user token
###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json  
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhY2FyZGkiLCJpZCI6IjYwN2VlZDNhYzg5Mjk1MTJmNjdmMDNhNCIsImlhdCI6MTYxODk0NjU2NX0.VpSzhuYaLNUHyBM76fowb5E-C5jRVXi4ltDX8i5qHEk

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0,
  "user": "607eed3ac8929512f67f03a4"
}


//POST with invalid user token
###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json  
Authorization: bearer eyJhbGciOiCI6IkpXVCJ9

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0,
  "user": "607eed3ac8929512f67f03a4"
}



//DELETE with different user from creator
###
DELETE http://localhost:3003/api/blogs/607ef5f9ad8bf81db9a1f2c3 HTTP/1.1
Content-Type: application/json  
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpc3RhY2NpbyIsImlkIjoiNjA3ZWVkM2VjODkyOTUxMmY2N2YwM2E1IiwiaWF0IjoxNjE4OTQ5MDcxfQ.rqpmgtUc4ZNdNn1m9YafPq-Kd-5fQHXyss798sIOdTQ

//DELETE without token
###
DELETE http://localhost:3003/api/blogs/607ef5f9ad8bf81db9a1f2c3 HTTP/1.1
Content-Type: application/json  

//DELETE with correct token and user
###
DELETE http://localhost:3003/api/blogs/607ef5f9ad8bf81db9a1f2c3 HTTP/1.1
Content-Type: application/json  
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhY2FyZGkiLCJpZCI6IjYwN2VlZDNhYzg5Mjk1MTJmNjdmMDNhNCIsImlhdCI6MTYxODk1MTY0Nn0.qWhT9BvbtX06TgcDgUWiqOFmFElMAnRSbHCJ3XQdPUk
