GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{
    "author": "something 2nd test",
    "title": "something 2nd",
    "url": "somethingend.com",
    "likes": 15
}