

//Blog requests
###
GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{
    "author": "something 2nd test",
    "title": "something 2nd",
    "url": "somethingend.com",
    "likes": 15
}

//User requests
###
GET http://localhost:3003/api/users HTTP/1.1


###
POST http://localhost:3003/api/users HTTP/1.1
content-Type: application/json

{
    "username": "bacardi",
    "name": "filipe",
    "password": "p@ssw0rd"
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-Type: application/json

{
    "username": "pistaccio",
    "name": "hyunjin",
    "password": "pVsswArd"
}


